
title: My photography workflow scripts
email: wwwwolf@iki.fi
description: >-
  My photography workflow scripts. Includes my photo importer script
  and random other tools.
domain: umbraroze.github.io
baseurl: /PhotoFlow/
url: https://umbraroze.github.io
github_username: umbraroze

#theme: midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
#  - jekyll-feed

