source "https://rubygems.org"

# JANK FIX - Needed for Jekyll
gem "csv"
gem "bigdecimal"
gem "fiddle"

#gem "jekyll", "~> 4.x.x" # Actual version resolved via github-pages
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "github-pages", "~> 228"
end
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
  gem "wdm", "~> 0.2.0"
end
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]

gem "webrick", "~> 1.8"
